resolver: nightly-2020-10-05
compiler: ghc-8.10.2

packages:
- .

extra-deps:
- smtp-mail-0.3.0.0

- github: PLSysSec/frankie
  commit: b9ee2c0f7667025d0d0ac3a43ded43d1d1d63c28

- github: storm-framework/storm
  commit: f746ff1bf4876ac55618224b41a1271db291608a

# LH stuff
- text-format-0.3.2
- Diff-0.3.4

- github: ucsd-progsys/liquid-fixpoint
  commit: 58e3123f41dedd6082177303bb4b6bf4349edf46

- github: ucsd-progsys/liquidhaskell
  commit: ad7f0cf5b86cb62fa855f3392bfa34f65225c4ed
  subdirs:
      - .
      - liquid-base
      - liquid-ghc-prim

